include: package:flutter_lints/flutter.yaml
linter:
  rules:
    always_use_package_imports: true
    always_declare_return_types: true
    use_key_in_widget_constructors: false
    require_trailing_commas: true
